/*
Oracle SQL example for 
ALL_CONSTRAINTS
ALL_CONS_COLUMNS
ALL_TAB_COLUMNS
DBA_TAB_COLUMNS
*/

-- Demo on ALL_CONSTRAINTS
SELECT * FROM ALL_CONSTRAINTS WHERE TABLE_NAME = 'EMPLOYEES';

-- Demo on ALL_CONS_COLUMNS
SELECT * FROM ALL_CONS_COLUMNS WHERE TABLE_NAME = 'EMPLOYEES';

-- Demo on ALL_TAB_COLUMNS
SELECT * FROM ALL_TAB_COLUMNS WHERE TABLE_NAME = 'EMPLOYEES';

-- Demo on DBA_TAB_COLUMNS
SELECT * FROM DBA_TAB_COLUMNS WHERE TABLE_NAME = 'EMPLOYEES';

