@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.sme.climatedata.controller.ClimateController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_113995 { 
   	label=sme
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1981273812 { 
   	label=climatedata
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   ClimateController1680784939[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ClimateController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   climateService: ClimateService [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ createClimateData(climateData: ClimateData): ResponseEntity&lt;ClimateData&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ deleteClimateData(id: Long): ResponseEntity&lt;Void&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getClimateDataById(id: Long): ResponseEntity&lt;ClimateData&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateClimateData(id: Long, climateData: ClimateData): ResponseEntity&lt;ClimateData&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ClimateServiceImpl1016663686[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ClimateServiceImpl</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   climateDataRepository: ClimateDataRepository [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ createClimateData(climateData: ClimateData): ClimateData</TD></TR>
<TR><TD ALIGN="LEFT" >+ deleteClimateData(id: Long)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getClimateDataById(id: Long): ClimateData</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateClimateData(id: Long, climateData: ClimateData): ClimateData</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
ClimateController1680784939 -> ClimateServiceImpl1016663686[arrowhead=none];
    
}
@enduml