/*
#######################################################################################
# PROJECT NAME: EMPLOYEE LEAVE MGMT SYSTEM
# SQUAD: ELM SQUAD
#  
# MEMBERS: ANBU
# NORMALIZATION LEVEL: 3NF
#
#######################################################################################
*/

-- TABLES -> EMPLOYEES, LEAVE, COMP_HOLIDAYS, LEAVE_BALANCE
-- TABLE EMPLOYEES - contains employee details - developed by Anbu. EMP_ID PK, EMP_NAME, MGR_ID, EMAIL, PHONE, SAL, DOJ
CREATE TABLE EMPLOYEES(EMP_ID INT,
    EMP_NAME VARCHAR(50) NOT NULL,
    MGR_ID INT,
    EMAIL VARCHAR(50),
    GENDER CHAR(1),
    PHONE NUMBER(10), 
	SAL NUMBER(10,2), 
    DOJ DATE DEFAULT SYSDATE,
    CONSTRAINT FK_EMP_MGR_ID FOREIGN KEY (MGR_ID) REFERENCES EMPLOYEES(EMP_ID),
    CONSTRAINT UQ_EMP_EMAIL UNIQUE(EMAIL),CONSTRAINT UQ_EMP_PHONE UNIQUE(PHONE),
    CONSTRAINT PK_EMP_EMP_ID PRIMARY KEY(EMP_ID),
	CONSTRAINT CK_EMP_SAL CHECK(SAL > 0),
	CONSTRAINT CK_EMP_PHONE CHECK(LENGTH(PHONE) = 10),
	CONSTRAINT CK_EMP_EMAIL CHECK(EMAIL LIKE '%@%.%'));

-- TABLE LEAVE - contains leave details - developed by Anbu. LEAVE_ID, EMP_ID, LEAVE_TYPE,  LEAVE_START_DATE, LEAVE_END_DATE, STATUS, APPROVER_ID
CREATE TABLE LEAVE
(
LEAVE_ID INT,
EMP_ID INT,
LEAVE_TYPE CHAR(2),
LEAVE_START_DATE DATE,
LEAVE_END_DATE DATE,
STATUS VARCHAR(50),
APPROVER_ID INT,
CONSTRAINT FK_LEAVE_EMP_ID FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES(EMP_ID),
CONSTRAINT FK_LEAVE_APPROVER_ID FOREIGN KEY (APPROVER_ID) REFERENCES EMPLOYEES(EMP_ID),
CONSTRAINT PK_LEAVE_LEAVE_ID PRIMARY KEY(LEAVE_ID),
CONSTRAINT CK_LEAVE_LEAVE_TYPE CHECK(LEAVE_TYPE IN ('AL', 'RH', 'ML', 'PL','MY'))
);

-- TABLE HOLIDAYS - contains holiday details - developed by Anbu. HOLIDAY_ID, HOLIDAY_DATE, HOLIDAY_DESC
CREATE TABLE COMP_HOLIDAYS
(
HOLIDAY_ID INT,
HOLIDAY_DATE DATE,
HOLIDAY_DESC VARCHAR(50),
CONSTRAINT PK_HOLIDAY_HOLIDAY_ID PRIMARY KEY(HOLIDAY_ID)
);

-- TABLE LEAVE_BALANCE - contains leave balance details - developed by Anbu. EMP_ID, LEAVE_TYPE, LEAVE_BALANCE
CREATE TABLE LEAVE_BALANCE
(
EMP_ID INT,
LEAVE_TYPE CHAR(2),
LEAVE_BALANCE INT,
CONSTRAINT FK_LB_EMP_ID FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES(EMP_ID),
CONSTRAINT PK_LB_EMP_ID_LEAVE_TYPE PRIMARY KEY(EMP_ID, LEAVE_TYPE),
CONSTRAINT CK_LB_LEAVE_BALANCE CHECK(LEAVE_BALANCE >= 0)
);

-- SEQ FOR EMP_ID IN EMPLOYEE TABLE
CREATE SEQUENCE EMP_ID_SEQ
START WITH 5600000
MAX VALUE 9999999
INCREMENT BY 1
CACHE 10
NOCYCLE;

-- REFERENCE VARIABLES in SEQUENCE - CURRVAL, NEXTVAL



-- DATA FOR EMPLOYEE TABLE
INSERT INTO EMPLOYEES VALUES(EMP_ID_SEQ.NEXTVAL, 'Anbu', NULL, 'anbu@hcltech.com', 'M', 9999999999, 10000.00, '01-JAN-2020');
INSERT INTO EMPLOYEES VALUES(EMP_ID_SEQ.NEXTVAL, 'Raj', 1, 'raj@hcltech.com', 'M', 8888888888, 20000.00, '01-JAN-2020');
INSERT INTO EMPLOYEES VALUES(EMP_ID_SEQ.NEXTVAL, 'Ravi', 1, 'ravi@hcltech.com', 'M', 7777777777, 30000.00, '01-JAN-2020');
COMMIT;

-- DATA FOR LEAVE TABLE
INSERT INTO LEAVE VALUES(1, 5600001, 'AL', '03-JAN-2024', '03-JAN-2024', 'PENDING', NULL);
INSERT INTO LEAVE VALUES(2, 5600002, 'RH', '03-JAN-2024', '03-JAN-2024', 'APPROVED', 5600000);
INSERT INTO LEAVE VALUES(3, 5600002, 'AL', '10-JAN-2024', '12-JAN-2024', 'PENDING', NULL);
COMMIT;

-- DATA FOR HOLIDAYS TABLE
INSERT INTO COMP_HOLIDAYS VALUES(1, '01-JAN-2024', 'New Year');
INSERT INTO COMP_HOLIDAYS VALUES(2, '26-JAN-2024', 'Republic Day');
INSERT INTO COMP_HOLIDAYS VALUES(3, '15-AUG-2024', 'Independence Day');
INSERT INTO COMP_HOLIDAYS VALUES(4, '02-OCT-2024', 'Gandhi Jayanthi');
COMMIT;

-- DATA FOR LEAVE_BALANCE TABLE
INSERT INTO LEAVE_BALANCE VALUES(5600000, 'AL', 10);
INSERT INTO LEAVE_BALANCE VALUES(5600000, 'RH', 5);
INSERT INTO LEAVE_BALANCE VALUES(5600001, 'AL', 9);
INSERT INTO LEAVE_BALANCE VALUES(5600001, 'RH', 5);
INSERT INTO LEAVE_BALANCE VALUES(5600002, 'AL', 7);
INSERT INTO LEAVE_BALANCE VALUES(5600002, 'RH', 4);
COMMIT;

-- LEAVE BALANCE DASHBOARD
-- MY LEAVE REQUESTS, 

-- VIEW FOR PENDING_LEAVES for APPROVAL
CREATE OR REPLACE VIEW PENDING_LEAVES AS
SELECT L.LEAVE_ID, E.EMP_NAME, L.LEAVE_TYPE, L.LEAVE_START_DATE, L.LEAVE_END_DATE, L.STATUS
FROM LEAVE L, EMPLOYEES E
WHERE L.EMP_ID = E.EMP_ID AND L.STATUS = 'PENDING';


--SELECT * FROM PENDING_LEAVES;


-- VIEW FOR ALL EMPLOYEES and its LEAVE details
CREATE OR REPLACE VIEW EMPLOYEE_LEAVE_DETAILS AS
SELECT E.EMP_ID, E.EMP_NAME, L.LEAVE_TYPE, L.LEAVE_START_DATE, L.LEAVE_END_DATE, L.STATUS
FROM LEAVE L
RIGHT JOIN EMPLOYEES E
ON L.EMP_ID = E.EMP_ID;

--SELECT * FROM EMPLOYEE_LEAVE_DETAILS;

-- ERD --> All the tables - COLUMNS with constraints (PK, FK, UQ, NN, CHECK). Cardinality - 1:M, M:M, 1:1, M:1

